set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",screen-256color*:Tc"
set -s escape-time 0
set -g base-index 1
setw -g mode-keys vi
set-option -g default-shell /usr/bin/zsh

# Use vim-like session/window/pane switching
bind -n C-y switch-client -n
bind -n C-h next-window
bind -n C-n select-pane -U

# Customize tmux's status bar
set-option -g status-position bottom
set -g status-left '#[bold] #S     (#{window_index} windows #F)'
set -g status-right '#[bold]#T '
set -g window-status-format "#[bold] #I:#W "
set -g window-status-current-format "#[bold] #I:#W* "
set -g status-style "bg=#6EDC39"

# Use custom scripts to open files, start sessions, and revisit snippets
bind -n ^a run-shell "tmux neww ~/.config/scripts/find_edit_file "
bind -n ^x run-shell "tmux neww ~/.config/scripts/tmux_sessionizer"
bind -n ^q run-shell "tmux split-window -p 70 -v ~/.config/scripts/tmux_cht"

# Copy to the system clipboard from within tmux's Vi mode
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
# bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Copy to system clipboard. Unnecesary given it is already configured in .zshrc
# set-window-option -g mode-keys vi
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# List of plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'