set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",screen-256color*:Tc"
set -s escape-time 0
setw -g mode-keys vi
setw -g mouse on
set-option -g status-left-length 25
set-option -g default-shell /usr/bin/zsh

# Use vim-like session/window/pane switching
bind -n C-y switch-client -n
bind -n C-h next-window
bind -n C-n select-pane -U

# Customize tmux's status bar
set-option -g status-position bottom
set -g status-left '#[bold] #S     '
set -g status-right '#[bold]#T '
set -g window-status-format "#[bold] #I:#W "
set -g window-status-current-format "#[bold] #I:#W* "
set -g status-style "bg=#6EDC39"

# Use custom scripts to open files, start sessions, and revisit snippets
bind -n ^a run-shell "tmux neww ~/.config/scripts/find_edit_file "
bind -n ^x run-shell "tmux neww ~/.config/scripts/tmux_sessionizer"

# Copy to the system clipboard from within tmux's Vi mode
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
# bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Add list of plugins. Don't seem to work.
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'