[bar/top]
monitor = ${env:MONITOR:}
width = 100%
height = 25
offset-x = 0
offset-y = 0
background = #222D32
foreground = #FFFFFF
radius = 0.0
fixed-center = true
font-0 = "DejaVu Sans Mono:size=9;2"

modules-left = i3
modules-right = xkeyboard wifi cpu memory backlight volume battery date

; Separator
separator = | 

; i3 workspaces
[module/i3]
type = internal/i3
label-mode = %mode%
label-mode-padding = 2
label-focused = %index%
label-focused-background = #0088CC
label-focused-padding = 2
label-unfocused = %index%
label-unfocused-padding = 2

; Date and Time
[module/date]
type = internal/date
interval = 1.0
date = %Y-%m-%d
time = %H:%M
format = <label>
label = %date% %time%

; Volume Control
[module/volume]
type = internal/alsa
label-muted = Vol: Muted
label-muted-foreground = #888888
label-volume = Vol: %percentage%%

; Ramp symbols to use for volume display
ramp-volume-0 = 奄
ramp-volume-1 = 奔
ramp-volume-2 = 婢

; Mute indicator
indicator-muted = 婢
indicator-muted-foreground = ${colors.foreground-alt}

; Battery
[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
format-charging = <label-charging>
format-discharging = <label-discharging>
label-charging = Charging: %percentage%%
label-discharging = Battery: %percentage%%

[module/backlight]
type = internal/backlight
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
use-actual-brightness = true
enable-scroll = true
format = <label>
label = Brightness: %percentage%%

; CPU usage
[module/cpu]
type = internal/cpu
interval = 1
format = <label>
label = "CPU: %percentage:2%%"

; RAM usage
[module/memory]
type = internal/memory
interval = 1
format = <label>
label = "RAM: %percentage_used%%"

[module/wifi]
type = internal/network
interface = "wlp4s0"
label-connected = "%essid% %downspeed:9%"
label-disconnected = "Not connected"
label-disconnected-foreground = #ff7777

[module/xkeyboard]
type = internal/xkeyboard
; List of indicators to ignore
blacklist-0 = num lock
blacklist-1 = scroll lock
