# The secrets and the public keys used to encrypt them.
# The private keys are referenced from the sops-nix config.
keys:
  - &personal age1g6hgtp8v3wyam384n8j4jxmm82f8a8ztxdpsxyxah4nnfe6kq5jqdfcfjy
  # - &work xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *personal
  # - path_regex: hosts/work/sops_secrets.yaml$
  #   key_groups:
  #   - age:
  #     - *work

# Create public and private keys:
# age-keygen -o age.key

# Define the secrets: 
# touch ~/.config/nixos/secrets_unencrypted.yaml

# Encrypt the secrets
# sops encrypt --age age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ~/.config/nixos/secrets_unencrypted.yaml > ~/.config/nixos/secrets/secrets.yaml

# Save the keys somewhere and:
# rm ~/.config/nixos/secrets_unencrypted.yaml
# rm age.key

